server:
  bind:
    host: 0.0.0.0
    port: 5000
  url: http://localhost:5000
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  gzip: false
  languages:
    - en-US
  pretty_print: false
  connected_systems: true
  limit: 10
  templates:
    path: /
  map:
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'

logging:
  level: ERROR
  #logfile: /tmp/pygeoapi.log

metadata:
  identification:
    title:
      en: connected-systems-pygeoapi
    description:
      en: OGC Connected-Systems API
    keywords:
      en:
        - geospatial
        - data
        - api
    keywords_type: theme
    terms_of_service:
    url: http://localhost
  license:
    name: CC-BY 4.0 license
    url: https://creativecommons.org/licenses/by/4.0/
  provider:
    name: 52°North Spatial Information Research GmbH
    url: https://52north.org
  contact:
    name: Speckamp, Jan
    position: Software Solutions Architect
    address: Martin-Luther-King-Weg 24
    city: Münster
    stateorprovince: NRW
    postalcode: 48155
    country: Germany
    phone: +49-251-396371-0
    email: j.speckamp+csa-development@52north.org
    url: https://52north.org/about-us/contact-us/
    hours: Mo-Fr 09:00-16:00
    instructions: During hours of service. Off on weekends.
    role: pointOfContact

resources: { }

dynamic-resources:
  csa-part1:
    type: connected-systems-part1
    title: "elasticsearch-csa-adapter"
    description: "Adapter to Elasticsearch CSA-Part1 Backend"
    strict_validation: True
    keywords: [ ]
    provider: &es-config
      type: elastic-csa-adapter
      name: ElasticSearchConnectedSystems
      host: localhost
      port: 9200
      dbname: csa
      user: elastic
      password: password
      verify_certs: False   # True if ES certificates are to be validated. Default 'true'
      ca_certs: ""   # Path to PEM-encoded Certificate of ES

  csa-part2:
    type: connected-systems-part2
    title: "timescale-csa-adapter"
    description: "Adapter to TimescaleDB CSA-Part2 Backend"
    keywords: [ ]
    provider:
      type: timescale-csa-adapter
      name: TimescaleDBConnectedSystems
      timescale:
        host: localhost
        port: 5432
        dbname: csa
        user: timescaledb
        password: password
      elastic: *es-config